### PR TITLE
returns home once logged in,without url extension

### PR DESCRIPTION
**Pull request by nurdtechie98**
<h1>Returns home once logged in</h1>
<p>Earlier once logged in the the host page without URL extension gave 404 so may be this is helpful <p>

### CODE REVIEW

**Review by inishchith — COMMENTED** [review]
Never encountered this problem . check webpanel/urls to get idea .

**Comment by Chaitya62** [comment]
Yep, can reproduce it, will pull it locally and  test it.

**Comment by Chaitya62** [comment]
Need a suggestion: will it make more sense in changing the redirect in [auth.py](https://github.com/Chaitya62/WebPanel/blob/master/login/middleWare/auth.py) or this one is fine.
@inishchith @Ankit-22 @nurdtechie98

**Comment by Ankit-22** [comment]
auth.py makes more sense because we also need a list of URLs in auth.py (The ones that don't require authentication). So if the Url is not from our list we can redirect without going to routes.

**Comment by Chaitya62** [comment]
@nurdtechie98 I think just undo the previous change using `git reset` and make changes in auth.py.

**Comment by inishchith** [comment]
resolved this issue? is someone assigned ? @Chaitya62 @nurdtechie98 @Ankit-22

**Comment by nurdtechie98** [comment]
I will do it

**Comment by Chaitya62** [comment]
The code should look something like 
```python
if '/' != request.get_full_path():
			print('checking....')
			if request.session.get('logged',False) is  True:
				print('Redirecting .....')
				return HttpResponseRedirect('/lhome/')
```
something similar should work

**Pull request closed without merging**
